from pygame import Vector2, Rect

# --------------------- CONSTANTES PYGAME ---------------------

LARGURA_TELA:           int     = 450
ALTURA_TELA:            int     = 700
FRAMERATE:              int     = 100

# --------------------- CONSTANTES DO JOGO ---------------------

VELOCIDADE_JOGO:        int     = -400 # VELOCIDADE DE REFERENCIA PARA OS ENFEITES DO JOGO

# --------------------- CONSTANTES DO CHAO ---------------------

QUANTIDADE_CHAO:        int     = 5 # QUATNIDADE DE CHAO
DIMENSOES_CHAO:         Vector2 = Vector2(209, 75) # LARGURA E ALTURA DO SPRITE DO CHAO
VELOCIDADE_CHAO:        Vector2 = Vector2(0.5*VELOCIDADE_JOGO, 0) # VELOCIDADE COM QUE O CHAO SE MOVE

# --------------------- CONSTANTES DA ARVORE ---------------------

QUANTIDADE_ARVORE:      int     = 3 # QUANTIDADE DE ARVORES
DIMENSOES_ARVORE:       Vector2 = Vector2(959, 52) # LARGURA E ALTURA DO SPRITE DO CHAO
VELOCIDADE_ARVORE:      Vector2 = Vector2(0.25*VELOCIDADE_JOGO, 0) # VELOCIDADE COM QUE AS ARVORES SE MOVEM

# --------------------- CONSTANTES DO PREDIO ---------------------

QUANTIDADE_PREDIO:      int     = 3 # QUANTIDADE DE PREDIOS
DIMENSOES_PREDIO:       Vector2 = Vector2(960, 54) # LARGURA E ALTURA DO SPRITE DOS PREDIOS
VELOCIDADE_PREDIO:      Vector2 = Vector2(0.15*VELOCIDADE_JOGO, 0) # VELOCIDADE COM QUE OS PREDIOS SE MOVEM

# --------------------- CONSTANTES DO NUVEM ---------------------

QUANTIDADE_NUVEM:       int     = 3 # QUANTIDADE DE NUVENS
DIMENSOES_NUVEM:        Vector2 = Vector2(959, 114) # LARGURA E ALTURA DO SPRITE DAS NUVENS
VELOCIDADE_NUVEM:       Vector2 = Vector2(0.05*VELOCIDADE_JOGO, 0) # VELOCIDADE COM QUE AS NUVENS SE MOVEM

# --------------------- CONSTANTES DO CANO ---------------------

QUANTIDADE_CANO:        int     = 3 # QUANTIDADE DE PARES DE CANO
DIMENSOES_CANO:         Vector2 = Vector2(86, 836) # LARGURA E ALTURA DO SPRITE CANO
VELOCIDADE_CANO:        Vector2 = Vector2(0.5*VELOCIDADE_JOGO, 0) # VELOCIDADE COM QUE OS CANOS SE MOVEM
DISTANCIA_ENTRE_CANOS:  int     = 170 # ESPAÇO ENTRE OS PARES DE CANOS
ABERTURA_CANO:          int     = 85 # TAMANHO DA ABERTURA DOS PARES DE CANO
CONSTANTE_RNG:          int     = 110 # QUANTIDADE DE PIXELS QUE AS ABERTURAS DOS CANOS VARIAM (TANTO PRA CIMA QUANTO PRA BAIXO)

# --------------------- CONSTANTES DO PASSARO ---------------------

CONSTANTE_GRAVITACIONAL: int    = 1000 # FORÇA QUE JOGA O PASSARO PARA O CHAO
POSICAO_INICIAL_PASSARO: Vector2 = Vector2(50, ALTURA_TELA // 3)
DIMENSOES_PASSARO: Vector2 = Vector2(50, 45) # LARGURA E ALTURA DO SPRITE DO PASSARO
FORCA_PULO = 350
VELOCIDADE_ANGULO = 80 # VELOCIDADE COM QUE O ANGULO DO PASSARO VARIA
HITBOX_PASSARO = Rect(
    POSICAO_INICIAL_PASSARO.x,
    POSICAO_INICIAL_PASSARO.y,
    DIMENSOES_PASSARO.x,
    DIMENSOES_PASSARO.y
)
